// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ILogger is an autogenerated mock type for the ILogger type
type ILogger struct {
	mock.Mock
}

type ILogger_Expecter struct {
	mock *mock.Mock
}

func (_m *ILogger) EXPECT() *ILogger_Expecter {
	return &ILogger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function with given fields: msg, args
func (_m *ILogger) Debug(msg string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// ILogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type ILogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - msg string
//   - args ...interface{}
func (_e *ILogger_Expecter) Debug(msg interface{}, args ...interface{}) *ILogger_Debug_Call {
	return &ILogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{msg}, args...)...)}
}

func (_c *ILogger_Debug_Call) Run(run func(msg string, args ...interface{})) *ILogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *ILogger_Debug_Call) Return() *ILogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *ILogger_Debug_Call) RunAndReturn(run func(string, ...interface{})) *ILogger_Debug_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function with given fields: msg, args
func (_m *ILogger) Error(msg string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// ILogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type ILogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - msg string
//   - args ...interface{}
func (_e *ILogger_Expecter) Error(msg interface{}, args ...interface{}) *ILogger_Error_Call {
	return &ILogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{msg}, args...)...)}
}

func (_c *ILogger_Error_Call) Run(run func(msg string, args ...interface{})) *ILogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *ILogger_Error_Call) Return() *ILogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *ILogger_Error_Call) RunAndReturn(run func(string, ...interface{})) *ILogger_Error_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function with given fields: msg, args
func (_m *ILogger) Info(msg string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// ILogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type ILogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - msg string
//   - args ...interface{}
func (_e *ILogger_Expecter) Info(msg interface{}, args ...interface{}) *ILogger_Info_Call {
	return &ILogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{msg}, args...)...)}
}

func (_c *ILogger_Info_Call) Run(run func(msg string, args ...interface{})) *ILogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *ILogger_Info_Call) Return() *ILogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *ILogger_Info_Call) RunAndReturn(run func(string, ...interface{})) *ILogger_Info_Call {
	_c.Call.Return(run)
	return _c
}

// NewILogger creates a new instance of ILogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewILogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *ILogger {
	mock := &ILogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
